Remove nix
diagridio/go-etcd-cron pull request #16
Opened 2024-05-03 19:38 UTC by JoshVanL

2024-05-06 19:58 UTC, cicoyle approved these changes

2024-05-07 21:45 UTC, cicoyle commented
Why are the tests failing on this diff?

2024-07-22 15:05 UTC, artursouza commented
The addition of Nix accidentally removed the lint check. @JoshVanL Please, fix the lint in the code once you have the time for us to merge this change. Thanks.

2024-07-22 15:33 UTC, artursouza requested changes
Also, miss the Makefile that was present here before.

2024-07-22 17:08 UTC, artursouza approved these changes

2024-07-22 17:08 UTC, merged