API: Adds DeletePrefixes
diagridio/go-etcd-cron pull request #37
Opened 2024-09-02 09:14 UTC by JoshVanL

Adds a new DeletePrefixes API which deletes all jobs (as well as counters) whose names match the given prefixes. Note the given strings to this API are prefixes of the _job names_, not the underlying ETCD keys. Prefixes will be serialized into the actual ETCD keys.

This is useful for Dapr to add a feature whereby jobs (of all of types) in a particular namespace (some job prefix) are deleted when a Kubernetes Namespace is deleted.

Moves `/internal/tests` to `/tests` to expose cron ETCD helper funcs for library consumers. Expands package with a `cron` sub-package to introduce single and clustered cron server setup helpers.

Exposes the `CounterGarbageCollectionInterval` time duration pointer option to enable testing time interval triggered counter garbage collection. This is set to a low value during some tests, which has a side effect of soft testing this doesn't prematurely delete counters.

Slight refactor of `api_test.go` to reside in a different package to prevent a circular import from `/tests`.

Adds `/fake` for exposing a fake cron that library consumers can use for testing.

2024-09-03 22:40 UTC, cicoyle commented on api.go
> -	counterKey := c.key.CounterKey(name)
Why is this being removed? Won't this cause counters to linger even when a job is removed?

2024-09-03 22:42 UTC, cicoyle commented on api.go
> +		resp, err := c.client.Delete(ctx, keyPrefix, clientv3.WithPrefix(), clientv3.WithPrevKV())
Don't we need to cleanup the counters here as well or am I missing that somewhere in the diff?

2024-09-03 22:45 UTC, cicoyle commented on cron.go
> +	c.collector.Push(c.key.CounterKey(c.key.JobName(e.Key)))
oh I see it here now

2024-09-03 22:53 UTC, cicoyle approved these changes

2024-09-04 13:39 UTC, JoshVanL commented on cron.go
> +	c.collector.Push(c.key.CounterKey(c.key.JobName(e.Key)))
:+1:

2024-09-04 14:33 UTC, artursouza approved these changes

2024-09-04 14:33 UTC, artursouza requested changes
Please, target main branch.

2024-09-04 14:34 UTC, artursouza commented
This change is too big for a patch. We can release 0.3

2024-09-04 14:42 UTC, JoshVanL commented
@artursouza makes sense- I have opened [this PR](https://github.com/diagridio/go-etcd-cron/pull/38) to fast forward master to keep up with release-0.2

2024-09-05 17:29 UTC, artursouza approved these changes

2024-09-05 17:29 UTC, artursouza approved these changes

2024-09-05 17:30 UTC, merged